In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import BayesianRidge
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
pd.set_option('display.max_columns', None)

In [14]:
df = pd.read_csv('games.csv')

In [15]:
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,0.382,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,0.457,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,0.313,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,0.297,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,0.378,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26646,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
26647,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
26648,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
26649,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
26650,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [16]:
df = df[['GAME_DATE_EST', 'GAME_ID', 'SEASON', 'TEAM_ID_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away', 'PTS_home', 'PTS_away', ]]

In [17]:
df

,GAME_DATE_EST,GAME_ID,SEASON,TEAM_ID_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,PTS_home,PTS_away
0,2022-12-22,22200477,2022,1610612740,0.484,0.926,0.382,25.0,46.0,1610612759,0.478,0.815,0.321,23.0,44.0,126.0,117.0
1,2022-12-22,22200478,2022,1610612762,0.488,0.952,0.457,16.0,40.0,1610612764,0.561,0.765,0.333,20.0,37.0,120.0,112.0
2,2022-12-21,22200466,2022,1610612739,0.482,0.786,0.313,22.0,37.0,1610612749,0.470,0.682,0.433,20.0,46.0,114.0,106.0
3,2022-12-21,22200467,2022,1610612755,0.441,0.909,0.297,27.0,49.0,1610612765,0.392,0.735,0.261,15.0,46.0,113.0,93.0
4,2022-12-21,22200468,2022,1610612737,0.429,1.000,0.378,22.0,47.0,1610612741,0.500,0.773,0.292,20.0,47.0,108.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26646,2014-10-06,11400007,2014,1610612737,0.419,0.821,0.421,24.0,50.0,1610612740,0.366,0.643,0.375,17.0,43.0,93.0,87.0
26647,2014-10-06,11400004,2014,1610612741,0.338,0.719,0.381,18.0,40.0,1610612764,0.411,0.636,0.267,17.0,47.0,81.0,85.0
26648,2014-10-06,11400005,2014,1610612747,0.448,0.682,0.500,29.0,45.0,1610612743,0.387,0.659,0.500,19.0,43.0,98.0,95.0
26649,2014-10-05,11400002,2014,1610612761,0.440,0.771,0.333,21.0,30.0,1610612758,0.469,0.725,0.385,18.0,45.0,99.0,94.0
26650,2014-10-04,11400001,2014,1610612748,0.431,0.679,0.333,18.0,42.0,1610612740,0.462,0.706,0.438,19.0,42.0,86.0,98.0